<a href="https://colab.research.google.com/github/talitamarques30/projeto_tse_2022/blob/main/src/projetoTse2022.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
%cd '/content/drive/My Drive/Tse colab/src'

/content/drive/My Drive/Tse colab/src

In [18]:
estado = pd.read_csv("perfil_eleitor_secao_2022_SP.csv",
                     usecols = '''NM_MUNICIPIO DS_ESTADO_CIVIL DS_FAIXA_ETARIA DS_GRAU_ESCOLARIDADE QT_ELEITORES_PERFIL QT_ELEITORES_INC_NM_SOCIAL'''.split(),
                     sep = ";", on_bad_lines = 'skip', encoding='Latin 1')
municipio = estado.query('NM_MUNICIPIO == "SÃO JOSÉ DOS CAMPOS" and NM_MUNICIPIO != "-1" and DS_ESTADO_CIVIL != "-1" and DS_FAIXA_ETARIA != "-1" and DS_GRAU_ESCOLARIDADE != "-1" and QT_ELEITORES_PERFIL != "-1" and QT_ELEITORES_INC_NM_SOCIAL != "-1"')
municipio = municipio.drop(columns = 'NM_MUNICIPIO')

In [19]:
dataFrame = pd.DataFrame(municipio)

In [20]:
dataFrame.sample(25)

,DS_ESTADO_CIVIL,DS_FAIXA_ETARIA,DS_GRAU_ESCOLARIDADE,QT_ELEITORES_PERFIL,QT_ELEITORES_INC_NM_SOCIAL
6537961,SOLTEIRO,30 a 34 anos,ENSINO MÉDIO COMPLETO,2,0
14582710,SOLTEIRO,45 a 49 anos,ENSINO FUNDAMENTAL INCOMPLETO,1,0
3436295,CASADO,60 a 64 anos,ENSINO FUNDAMENTAL COMPLETO,1,0
5072561,CASADO,45 a 49 anos,ENSINO FUNDAMENTAL COMPLETO,1,0
4180774,SOLTEIRO,18 anos,ENSINO MÉDIO COMPLETO,2,0
4954258,SOLTEIRO,50 a 54 anos,SUPERIOR COMPLETO,1,0
5825110,CASADO,30 a 34 anos,ENSINO MÉDIO COMPLETO,1,0
2783225,CASADO,30 a 34 anos,ENSINO MÉDIO COMPLETO,1,0
2539538,SOLTEIRO,40 a 44 anos,ENSINO FUNDAMENTAL INCOMPLETO,1,0
5535562,SOLTEIRO,40 a 44 anos,ENSINO MÉDIO INCOMPLETO,1,0
3322076,CASADO,35 a 39 anos,SUPERIOR COMPLETO,1,0
4880295,VIÚVO,65 a 69 anos,ENSINO FUNDAMENTAL COMPLETO,2,0
4273971,CASADO,35 a 39 anos,ENSINO MÉDIO COMPLETO,2,0
2543646,CASADO,55 a 59 anos,SUPERIOR INCOMPLETO,1,0
5073943,CASADO,50 a 54 anos,ENSINO MÉDIO COMPLETO,4,0
696037,SOLTEIRO,50 a 54 anos,SUPERIOR COMPLETO,1,0
1592085,VIÚVO,75 a 79 anos,ENSINO FUNDAMENTAL INCOMPLETO,1,0
1426299,SOLTEIRO,21 a 24 anos,ENSINO MÉDIO COMPLETO,2,0
1692996,SOLTEIRO,45 a 49 anos,ENSINO FUNDAMENTAL COMPLETO,1,0
4959769,VIÚVO,85 a 89 anos,LÊ E ESCREVE,1,0
1710852,CASADO,35 a 39 anos,ENSINO MÉDIO COMPLETO,4,0
727776,SOLTEIRO,35 a 39 anos,ENSINO MÉDIO INCOMPLETO,1,0
4988637,SOLTEIRO,50 a 54 anos,ENSINO MÉDIO INCOMPLETO,1,0
5773368,CASADO,40 a 44 anos,ENSINO MÉDIO INCOMPLETO,1,0
3718051,CASADO,60 a 64 anos,SUPERIOR INCOMPLETO,1,0

In [21]:
#Classificação à partir de Estado Civil, Faixa Etária, Escolaridade
estado_civil = dataFrame.groupby('DS_ESTADO_CIVIL')['QT_ELEITORES_PERFIL'].sum().sort_values(ascending=False)
faixa_etaria = dataFrame.groupby('DS_FAIXA_ETARIA')['QT_ELEITORES_PERFIL'].sum().sort_values(ascending=False)
escolaridade = dataFrame.groupby('DS_GRAU_ESCOLARIDADE')['QT_ELEITORES_PERFIL'].sum().sort_values(ascending=False)

In [26]:
#Qtd eleitores nome social
nome_social = dataFrame.groupby('QT_ELEITORES_INC_NM_SOCIAL')['QT_ELEITORES_PERFIL'].count()

QT_ELEITORES_INC_NM_SOCIAL
0    254646
1       121
Name: QT_ELEITORES_PERFIL, dtype: int64

In [23]:
#Características do eleitorado de acordo com representante eleito
estado_boletim = pd.read_csv("bweb_2t_SP_311020221535.csv", usecols = '''NM_MUNICIPIO SG_PARTIDO QT_COMPARECIMENTO QT_ABSTENCOES
                                                                        NM_VOTAVEL QT_VOTOS DS_CARGO_PERGUNTA'''.split(),
                             sep = ";", on_bad_lines='skip', encoding='Latin 1')

municipio = estado_boletim.query('NM_MUNICIPIO == "SÃO JOSÉ DOS CAMPOS" and DS_CARGO_PERGUNTA == "Presidente"')
municipio = municipio.drop(columns = 'NM_MUNICIPIO')

In [24]:
dataFrame_b = pd.DataFrame(municipio)

In [27]:
QTD_VOTOS = dataFrame_b.groupby('DS_CARGO_PERGUNTA')['QT_VOTOS'].sum().sort_values(ascending=False)
NOME_VOTAVEL = dataFrame_b.groupby('NM_VOTAVEL')['QT_VOTOS'].sum().sort_values(ascending=False)
QTD_VOTOS

NM_VOTAVEL
JAIR BOLSONARO    267615
LULA              159996
Nulo               14808
Branco              8176
Name: QT_VOTOS, dtype: int64